from typing import TypedDict, List, Dict, Any, Optional
from app.models.candidate import Candidate
from app.models.position import Position
import uuid


class RecruitingState(TypedDict):
    """
    State for the recruiting loop agent.

    Fields flow through the LangGraph StateGraph pipeline:
    search -> dedup -> score -> pipeline -> outreach -> evaluate
    """

    # Core entities
    position: Position
    keywords: List[str]
    candidates: List[Dict[str, Any]]
    dedup_result: List[Dict[str, Any]]
    pipeline_updates: List[Dict[str, Any]]

    # Scoring metadata (populated by score_node)
    score_details: List[Dict[str, Any]]

    # Outreach emails generated by outreach_node
    outreach_emails: List[Dict[str, Any]]

    # Metrics & control
    metrics: Dict[str, int]
    errors: List[str]
    continue_loop: bool
    run_id: Optional[uuid.UUID]